# Generated by Django 4.0.1 on 2022-01-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorimodel',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
    ]
